name: F-Droid Build

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set FDROID_BUILD environment variable
        run: echo "FDROID_BUILD=1" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :app:fdroidRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-fdroid-release
          path: app/build/outputs/apk/fdroid/release/*.apk
